name: shahid_neshan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  google_mlkit_text_recognition: ^0.14.0
  flutter_tesseract_ocr: ^0.4.24
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_map: ^6.1.0
  get_it: ^8.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tessdata/
    - assets/tessdata_config.json
    - assets/icon/
    - assets/images/

  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/data_medium.ttf
        - asset: assets/fonts/data_bold.ttf
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  