name: shahid_neshan
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_map: ^6.1.0
  dio: ^5.7.0
  get_it: ^8.0.2
  latlong2: ^0.9.1
  smooth_page_indicator: ^1.2.0+3
  story: ^1.1.0
  geolocator: ^11.1.0
  flutter_svg: ^2.0.10
  win32: ^5.0.9
  webview_flutter: ^4.5.0
  animated_snack_bar: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/icon/
    - assets/images/
    - assets/images/posts/
    - assets/images/shahid_images/

  fonts:
      - family: Dana
        fonts:
          - asset: assets/fonts/DANA_MEDIUM.TTF
            style: normal
            weight: 500
          - asset: assets/fonts/DANA_BLACK.TTF
            style: normal
            weight: 600
          - asset: assets/fonts/DANA_BOLD.TTF
            style: normal
            weight: 700
          - asset: assets/fonts/DANA_EXTRABOLD.TTF
            style: normal
            weight: 800
          - asset: assets/fonts/DANA_EXTRALIGHT.TTF
            style: normal
            weight: 100
          - asset: assets/fonts/DANA_LIGHT.TTF
            style: normal
            weight: 300
          - asset: assets/fonts/DANA_REGULAR.TTF
            style: normal
            weight: 400